# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # set the VM
  config.vm.box = "Centos/7"
  
  # set the IP
  config.vm.network "private_network", ip: "192.168.10.30"
  
  # Assign the local key to the vagrant user
  config.vm.provision "shell",
    inline: "cat /vagrant/vagrant_ssh/vagrant_rsa.pub >> /home/vagrant/.ssh/authorized_keys"

end